In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def plt_show(img):
    plt.axis('off')
    plt.imshow(img, cmap='gray')
    plt.show()

In [3]:
def cv_show(img):
    cv2.imshow("Mean Filtered Image", img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [4]:
def Blur(img, k):
    return cv2.blur(img, (k, k)).astype(np.uint8)

In [5]:
def filterImage(img, k):
    mask = np.ones([k, k], dtype='float16') / 9
    #mask = np.array([[1,2,1], [2,4,2], [1,2,1]], dtype='float16)
    #mask = mask/16
    return cv2.filter2D(img, -1, mask)

In [6]:
gray = cv2.imread("../../images/lena_salt_512.png", 0)
print(gray)

[[162 162   0 ... 170 155 128]
 [162 255 162 ... 170 155 128]
 [162 162 162 ... 170 155 128]
 ...
 [ 43  43  50 ... 104 100  98]
 [ 44  44  55 ... 104 105 108]
 [ 44  44  55 ... 104 105 108]]


In [12]:
blur_img = Blur(gray, 5)
#blur_img = cv2.blur(gray, (3,3)).astype(np.uint8)
imgs = cv2.hconcat([gray, blur_img])
cv_show(imgs)

In [8]:
def filterImage(img, k):
    #mask = np.ones([k, k], dtype = 'float16)/ (k**2)
    mask = np.array([[1,2,1],[2,4,2],[1,2,1]], dtype='float16')     
    mask = mask/16
    return cv2.filter2D(img, -1, mask).astype(np.unit8)

In [13]:
def filterCustom(img, k):
    mask = np.ones([k,k], dtype = 'float16')/ (k**2)
    #mask = np.array([[1,2,1],[2,4,2],[1,2,1]], dtype='float16')     
    #mask = mask/16
    (m,n) = img.shape
    #out = np.zeros((m,n), dtype = 'float16')
    #out = np.zeros_like(img, dtype = 'float')
    out = img.copy()
    bd = int(k/2)
    for i in range(bd,m-bd):
        for j in range(bd,n-bd):
            sub_f = img[i - bd : i + bd + 1, j - bd : j + bd + 1].astype(np.float16)
            out[i, j] = np.multiply(sub_f, mask).sum()    
    return out.astype(np.uint8)

In [14]:
blur_img = filterCustom(gray, 7)
imgs = cv2.hconcat([gray, blur_img])
cv_show(imgs)