In [1]:
import _pickle as cPickle
import numpy as np

In [2]:
class Mat(object):
    def __init__(self, x):
        self.mat = x

In [3]:
try:
    with open("Object_Matrix.bin", "wb") as fp:
        for i in range(5):
            x = np.random.randint(10,30, size=(5, 5))
            print(x)
            ob_mat = Mat(x)
            cPickle.dump(ob_mat,fp)
except Exception as e:
    print(e.__class__,e.args[1])

[[22 17 15 17 25]
 [21 17 21 19 17]
 [29 29 17 19 14]
 [18 14 11 10 20]
 [29 19 19 28 28]]
[[15 26 23 28 27]
 [10 27 28 26 11]
 [16 29 16 24 12]
 [29 16 16 19 14]
 [23 20 19 18 18]]
[[10 11 12 25 17]
 [24 29 11 18 26]
 [11 22 19 23 21]
 [12 23 22 24 28]
 [28 19 17 14 12]]
[[10 15 10 22 25]
 [12 23 11 22 14]
 [15 17 24 26 11]
 [11 13 27 19 18]
 [20 29 17 10 19]]
[[19 10 22 13 26]
 [14 24 20 20 12]
 [25 15 17 28 20]
 [11 27 17 10 18]
 [12 20 19 23 22]]


In [4]:
try:
    with open("Object_Matrix.bin", "rb") as fp:
        for i in range(5):
            ob = cPickle.load(fp)
            if not ob:
                break
            else:
                print(ob.mat)
except EOFError:
    print("something Wrong")

[[22 17 15 17 25]
 [21 17 21 19 17]
 [29 29 17 19 14]
 [18 14 11 10 20]
 [29 19 19 28 28]]
[[15 26 23 28 27]
 [10 27 28 26 11]
 [16 29 16 24 12]
 [29 16 16 19 14]
 [23 20 19 18 18]]
[[10 11 12 25 17]
 [24 29 11 18 26]
 [11 22 19 23 21]
 [12 23 22 24 28]
 [28 19 17 14 12]]
[[10 15 10 22 25]
 [12 23 11 22 14]
 [15 17 24 26 11]
 [11 13 27 19 18]
 [20 29 17 10 19]]
[[19 10 22 13 26]
 [14 24 20 20 12]
 [25 15 17 28 20]
 [11 27 17 10 18]
 [12 20 19 23 22]]
